/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

/**
 *
 * @author price
 */
public class MonedasFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MonedasFrame() {
        initComponents();
    }

    double new_cantidad;
    int tipo_menu;
    
    public void seleccionador(int num_menu, double cantidad) {
        FinalFrame finalFrame = new FinalFrame();
        switch (num_menu) {
            case 0:
                this.new_cantidad = cantidad*0.055;
                finalFrame.texto(this.new_cantidad, "dolares");
                break;
            case 1:
                this.new_cantidad = cantidad*0.052;
                finalFrame.texto(this.new_cantidad, "Euros");
                break;
            case 2:
                this.new_cantidad = cantidad*0.046;
                finalFrame.texto(this.new_cantidad, "Libras Esterlinas");
                break;
            case 3:
                this.new_cantidad = cantidad*7.55;
                finalFrame.texto(this.new_cantidad, "Yen Japones");
                break;
            case 4:
                this.new_cantidad = cantidad*72.37;
                finalFrame.texto(this.new_cantidad, "Won sul-coreano");
                break;
            case 5:
                this.new_cantidad = cantidad*18.12;
                finalFrame.texto(this.new_cantidad, "MXN");
                break;
            case 6:
                this.new_cantidad = cantidad*19.18;
                finalFrame.texto(this.new_cantidad, "MXN");
                break;
            case 7:
                this.new_cantidad = cantidad*21.52;
                finalFrame.texto(this.new_cantidad, "MXN");
                break;
            case 8:
                this.new_cantidad = cantidad*0.13;
                finalFrame.texto(this.new_cantidad, "MXN");
                break;
            case 9:
                this.new_cantidad = cantidad*0.014;
                finalFrame.texto(this.new_cantidad, "MXN3");
                break;
            default:
                throw new AssertionError();
        }
        finalFrame.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        menu_label = new javax.swing.JLabel();
        menu_options = new javax.swing.JComboBox<>();
        aceptar_btn = new javax.swing.JButton();
        cancelar_btn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel3.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(234, 231, 231));
        jPanel9.setLayout(null);

        menu_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_label.setText("Elije la moneda a la que quieres convertir");
        jPanel9.add(menu_label);
        menu_label.setBounds(30, 20, 260, 20);

        menu_options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos mexicanos a dólar", "Pesos mexicanos a Euros", "Pesos mexicanos a Libras Esterlinas", "Pesos mexicanos a Yen Japonés", "Pesos mexicanos a Won sul-coreano", "Convertir de Dólar pesos mexicanos", "Convertir de Euros pesos mexicanos", "Convertir de Libras Esterlinas pesos mexicanos", "Convertir de Yen Japonés pesos mexicanos", "Convertir de Won sul-coreano pesos mexicanos" }));
        jPanel9.add(menu_options);
        menu_options.setBounds(50, 50, 200, 30);

        aceptar_btn.setText("Aceptar");
        aceptar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptar_btnMouseClicked(evt);
            }
        });
        aceptar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_btnActionPerformed(evt);
            }
        });
        jPanel9.add(aceptar_btn);
        aceptar_btn.setBounds(60, 90, 80, 23);

        cancelar_btn.setText("Cancelar");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });
        jPanel9.add(cancelar_btn);
        cancelar_btn.setBounds(165, 90, 80, 23);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 310, 150);

        getContentPane().add(jPanel3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_btnActionPerformed
        tipo_menu = menu_options.getSelectedIndex();
        seleccionador(0, CantidadFrame.cantidad);
    }//GEN-LAST:event_aceptar_btnActionPerformed

    private void aceptar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptar_btnMouseClicked
        
    }//GEN-LAST:event_aceptar_btnMouseClicked

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
        new CantidadFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonedasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonedasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_btn;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel menu_label;
    private javax.swing.JComboBox<String> menu_options;
    // End of variables declaration//GEN-END:variables
}
